/*
 * File: app/view/LoginScreen.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Training.view.LoginScreen', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.TitleBar',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Training'
            },
            {
                xtype: 'textfield',
                id: 'username',
                margin: 5,
                label: '',
                placeHolder: 'User name'
            },
            {
                xtype: 'passwordfield',
                id: 'password',
                margin: 5,
                label: '',
                placeHolder: 'Password'
            },
            {
                xtype: 'button',
                id: 'loginbutton',
                margin: 60,
                ui: 'confirm',
                width: '50%',
                text: 'Login'
            }
        ]
    }

});